### ISSUE TITLE
Add support for joint_path_command service

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#11]
As mandated by the [_Industrial Robot Driver Specification_](http://www.ros.org/wiki/Industrial/Industrial_Robot_Driver_Spec), section 1.3.3, under _Services_:

> - joint_path_command ([industrial_msgs/CmdJointTrajectory](http://ros.org/doc/api/industrial_msgs/html/srv/CmdJointTrajectory.html))
>   - execute a new motion trajectory on the robot
>   - identical functionality to the joint_path_command topic
>   - the service-implementation allows calling code to receive confirmation that a commanded trajectory has actually been received by a robot node.

**Comment by shaun-edwards** [comment]
Does fanuc use or inherit from the generic clients.  It would be nice to implement this in the generic clients, so that all robots can have this ability.

**Comment by JeremyZoss** [comment]
industrial_robot_client does support this (see [here](https://github.com/ros-industrial/industrial_core/blob/groovy-devel/industrial_robot_client/src/joint_trajectory_interface.cpp#L105) and [here](https://github.com/ros-industrial/industrial_core/blob/groovy-devel/industrial_robot_client/src/joint_trajectory_interface.cpp#L118)).

The problem is that this service currently always returns SUCCESSFUL.  It is built by wrapping the existing messsage-publish callback, which returns void, so we can't determine whether it succeeded or not.

A better solution would be to have the TOPIC callback wrap the SERVICE callback, or create a common function that both callbacks reference.  However, due to the derived-class nature of industrial_robot_client, I considered this kind of change to be a "breaking" change for existing code.  It should be scheduled for "future" releases, not back-ported.  That being said, I don't know that this change will _actually_ break any existing code.

PS - If we are planning to modify the industrial_robot_client API for future releases, I have a set of other changes (in fs100 package) that I would like to push out to the "standard" industrial_robot_client packages.  This would help support migrating drivers to the newer joint_traj_pt_full and joint_feedback message types, also.

**Comment by gavanderhoorn** [comment]
@shaun-edwards

> Does fanuc use or inherit from the generic clients. It would be nice to implement this in the generic clients, so that all robots can have this ability.

The `fanuc_driver` subclasses `industrial_robot_client`, so it should support everything the default classes support.

I agree with the issue @JeremyZoss describes: the services should be able to report whether the robot actually performed the requested action. This should be possible, as the `simple_message` protocol allows for service return values. I'm not sure about the proposed implementation though, but I think that is a bit off-topic for this issue.

**Comment by gavanderhoorn** [comment]
In general this issue was just a "make sure the current implementation supports the mandated functionality" type of issue. As the base `industrial_robot_client` classes already expose this, this issue can be closed.

As to the report-actual-service-result issue, I'll create a new issue at `industrial_robot_client`.
