### ISSUE TITLE
moveit_cfg: allow user to switch to KDL based IK

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#112]
All currently provided MoveIt configurations have the provided IKFast plugins as there default -- and only -- IK plugin. For whatever reason, users might want to use the default KDL based IK (or something else), which would require manually changing `config/kinematics.yaml`.

Switching between the IKFast and the KDL plugins should be made possible using launch file parameters. The file `planning_context.launch` uploads the kinematics parameters to the parameter server, and could be extended for this purpose.

**Comment by gavanderhoorn** [comment]
Alternatively, users could override the parameters defined in `config/kinematics.yaml` before starting any of the involved MoveIt nodes.

**Comment by JeremyZoss** [comment]
I disagree with the need for this enhancement, even though it is a good suggestion.

My feeling is that the "stock" moveIt config packages are provided mostly for convenience and testing.  Any "real" application will likely use a newly-generated MoveIt package with different workcell or end-effector components defined in the collision environment.  When users create the new MoveIt package, they can select the appropriate kinematics plugin, if desired.

I see this as different than the core fanuc_driver (and model-specific _support) package.  We would, ideally, prefer that users be able to build on these packages as-is, extending (rather than modifying) the base package for their own needs.  Adding options to these lower-level support packages facilitates this re-use model.  The MoveIt config package does not lend itself to similar extension, and users will probably just re-generate their own MoveIt packages instead.

Another downside to modifying the MoveIt package to accept kinematics-switching launch-file flags is that this will deviate from the auto-generated MoveIt package.  Which makes it more difficult to keep these files in-sync with the standard MoveIt templates when the core MoveIt developers make updates to those files.

Just my thoughts...

**Comment by shaun-edwards** [comment]
While I agree each user might create their own MoveIt package, I don't think they will want to create an IK fast solution.  Although I haven't created a fast IK solution in a while, it was a pain in the past (if I am wrong please let me know).  Furthermore, an IK solution should be specific to a model, no matter what is added to (end-effector or otherwise).  Is there a way to create reusable IK solutions?

**Comment by JeremyZoss** [comment]
I think this issue is not about creating model-specific IKFast plugins, but about modifying the MoveIt package launch files to allow you to more easily switch between KDL and IKFast kinematic solutions.

I agree that creating model-specific IKFast plugins is helpful, as the IKFast process requires some extra dependencies and steps that may not be familiar to the average user.  As long as we are explicit (or consistent) about which frames are used for the IKFast solution (e.g. base_link to tool0), it should be portable across different MoveIt applications.

I think the only requirement is that the "planning group" defined in the MoveIt package matches the links used when creating the IKFast plugin.  This does require a few extra steps if the user wants to specify Cartesian Goals to MoveIt relative to different frames (e.g. world, TCP), but there are already provisions for this inside of MoveIt.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: @JeremyZoss is right, this issue is about the ability to switch between KDL and IKFast plugins. I've had some users that ran into a problem where the provided IKFast plugin was unable to come up with any solutions, while the KDL plugin had no problem. The only way (afaik) to change the used plugin is by editing the `kinematics.yaml` file.

As far as I understood, the IKFast plugins can indeed be reused, even in extended MoveIt configurations, as they are a property of the planning group (pkgs with multiple groups have multiple entries in their `kinematics.yaml`).

I'll leave this open for now. It is only a minor issue, but I wanted to document the fact that it has received some attention.

**Comment by gavanderhoorn** [comment]
Not going to do this.

Configuring a different IK solver is something that is documented in [MoveIt! Setup Assistant - Step 4: Add Planning Groups](https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html#step-4-add-planning-groups) (and other places), so users are expected to be able to do that themselves.
